### ISSUE TITLE
Alternative smilies

### ISSUE THREAD

**Issue by Alxandr** [bitjson/wip#1]
My shell doesn't support the images used by `wip`.

![image](https://cloud.githubusercontent.com/assets/112334/13554490/67ca9ef6-e3a9-11e5-8489-cb80f3c7e69e.png)

Would be great to have the option to use some ascii-art or similar instead, that works on all shells.

**Comment by bitjson** [comment]
Hey @Alxandr thanks for the report. Are you on Windows?

Could you see if any emoji is supported in the shell? Maybe try copy and pasting from here: [http://emojipedia.org/microsoft/](http://emojipedia.org/microsoft/)

If not, ascii art is a great idea for a fallback. (Though it would require more lines and might bloat the already-large boxes – we might need to just fall back to text-only.)

**Comment by Alxandr** [comment]
My terminal (seemingly) only supports ANSII unfortunately. I've been trying to figure out how I can get it to support more, but yeah. Might be the font, not sure.

Also, when I said ASCII-art I meant something simple like `:)` etc. Not multi-line stuff. Just simple smileys from the pre-unicode days :P

**Comment by bitjson** [comment]
Oh, that makes sense. Any idea how we can test for support?

**Comment by Alxandr** [comment]
No, not really. I was thinking just make it configurable, like the sounds.

**Comment by bitjson** [comment]
https://github.com/bitjson/wip/commit/6a24b6e8408cbce5c7aea3149871b5885afd7662

**Comment by bitjson** [comment]
Hey @Alxandr – this is now available in the latest release:
`$ wip without emoji`

Thanks!
